CREATE TABLE posts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    excerpt text,
    slug text NOT NULL UNIQUE,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    date date,
    read_time text,
    category text
);
